// tests/fixtures/staging-config.js
// Overwrites js/config.js with staging credentials before E2E tests run.
// Called by CI as: node tests/fixtures/staging-config.js
// Reads from environment variables set as GitHub Secrets.

import { writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '../..');

const url    = process.env.STAGING_SUPABASE_URL;
const key    = process.env.STAGING_SUPABASE_ANON_KEY;
const worker = process.env.STAGING_WORKER_URL;

if (!url || !key || !worker) {
  console.error('Missing required env vars: STAGING_SUPABASE_URL, STAGING_SUPABASE_ANON_KEY, STAGING_WORKER_URL');
  process.exit(1);
}

const content = `// js/config.js — AUTO-GENERATED by tests/fixtures/staging-config.js — DO NOT EDIT
const CONFIG = {
  supabaseUrl: '${url}',
  supabaseKey: '${key}',
  workerUrl:   '${worker}',
};
`;

writeFileSync(resolve(root, 'js/config.js'), content, 'utf8');
console.log('✓ js/config.js overwritten with staging credentials');
